### ISSUE TITLE
All the accounts come out as error 

### ISSUE THREAD

**Issue by Preasx24** [ZLaxtert/paypal-checkerV1.0#2]

**Comment by ZLaxtert** [comment]
If you want to run the tool, you must have the API and APIKEY to run the tool.

**Comment by LacDeptrai** [comment]
> If you want to run the tool, you must have the API and APIKEY to run the tool.

how can i have api ?

**Comment by ZLaxtert** [comment]
you can buy it apikey in my site https://darkxcode.site
